
# Ubuntu 22.04 (Jammy Jellyfish) 
dist: jammy

language: cpp
sudo: true
compiler: c++

before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - valgrind
      - cmake
      - googletest

install:
  - cd /usr/src/googletest
  - sudo cmake -Bbuild
  - sudo cmake --build build
  - sudo cmake --install build
  - sudo cmake --install build

script:
  - cd $TRAVIS_BUILD_DIR
  - make
  - make check
  - make check/leaks
