
language: cpp
sudo: true
compiler: c++

# TODO think about this
# cache:
#   directories:
#     - $TRAVIS_BUILD_DIR/res

before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - valgrind
      - cmake
      - libgtest-dev

install:
  - cd res
  - tar -xf googletest-1.13.0.tar.gz
  - cd googletest-1.13.0
  - mkdir build
  - cd build
  - cmake build ..
  - cd ..
  - cmake --build build
  - cd ./build/googlemock/
  - sudo make install

script:
  - cd $TRAVIS_BUILD_DIR
  - make
  - make check
  - make check/leaks
