
language: cpp
sudo: true
cache: package
compiler: c++

addons:
  apt:
    packages:
      - valgrind
      - cmake
      - libgtest-dev

install:
  - export CXX="/usr/bin/c++"
  - cd res
  - tar xf release-1.8.0.tar.gz
  - mv googletest-release-1.8.0 gtest
  - cd gtest
  - cmake -DBUILD_SHARED_LIBS=ON .
  - make
  - cp -a googletest/include/gtest /usr/include
  - cp -a googlemock/gtest/libgtest_main.so googlemock/gtest/libgtest.so /usr/lib/ 
  - cp -a googlemock/gtest/libgtest_main.so googlemock/gtest/libgtest.so ..
  - make install

script:
  - cd $TRAVIS_BUILD_DIR
  - make
  - make check
