
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install:
  - sudo cp -a res/gtest/googletest/include/gtest /usr/include

language: cpp

compiler: c++

script:
  - make test
