
language: cpp
sudo: true
compiler: c++

# TODO think about this
# cache:
#   directories:
#     - $TRAVIS_BUILD_DIR/res

addons:
  apt:
    packages:
      - valgrind
      - cmake
      - libgtest-dev

install:
  - export CXX="/usr/bin/c++"
  - cd res
  - tar xf release-1.8.0.tar.gz
  - mv googletest-release-1.8.0 gtest
  - cd gtest
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a googletest/include/gtest /usr/include
  - sudo cp -a googlemock/gtest/libgtest_main.so googlemock/gtest/libgtest.so /usr/lib/ 
  - sudo cp -a googlemock/gtest/libgtest_main.so googlemock/gtest/libgtest.so ..
  - sudo make install

script:
  - cd $TRAVIS_BUILD_DIR
  - make
  - make check
