
install:
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake
  - cd /usr/src/gtest
  - sudo mkdir build
  - cd build
  - sudo cmake ..
  - sudo make
  - sudo make install


language: cpp

compiler: clang

script:
  - make
  - ./webserv
