

install:
  - sudo cp -a res/gtest/googletest/include/gtest /usr/include

language: cpp

compiler: clang

script:
  - make
  - ./webserv
  - export LDFLAGS="-Wl,--copy-dt-needed-entries"
  - make test
