version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    ports:
      - 80:80
      - 90:90
    networks:
      frontend:
        ipv4_address: 172.20.0.5
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/usr/share/nginx/html

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24