<?php
header("Content-Type: text/html");

echo "<!DOCTYPE html>";
echo "<html>";
echo "<head>";
echo "<title>Simple HTML Page</title>";
echo "</head>";
echo "<body>";
echo "<h1>Hello, World!</h1>";
echo "<p>This is a simple HTML page generated by PHP.</p>";
echo "</body>";
echo "</html>";

?>
