
version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    networks:
      frontend:
        ipv4_address: 172.20.0.5
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./php:/usr/share/nginx/html
      - ./html:/var/www/html
  
  php:
    image: php:fpm-alpine
    container_name: php
    ports:
      - 9000:9000
    networks:
      frontend:
        ipv4_address: 172.20.0.6
    volumes:
      - ./php:/var/www/html

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24