
version: '3'

services:
  nginx:
    build: .
    container_name: nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./www.conf:/etc/php/7.3/cgi/conf.d/www.conf
      - /Users/yrabby/webserv/res/nginx/html:/usr/share/nginx/html/
  