
version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    networks:
      - net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
  
  php:
    image: php:fpm-alpine
    container_name: php
    ports:
      - 9000:9000
    networks:
      - net
    volumes:
      - ./html:/var/www/html

  py:
    build: .
    container_name: py
    ports:
      - 9001:9001
    networks:
      - net
    volumes:
      - ./html:/var/www/html

networks:
  net:
    driver: bridge