name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: webserv CI
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: ./script/install_dependencies.sh

    - name: Run Google Tests
      run: make check

    - name: Check For Leaks
      run: make check/leaks
